### ISSUE TITLE
Create Metadata database

### ISSUE THREAD

**Issue by biglimp** [geovetarcentrum/climate-stations#1]
Could we also start a metadata database (maybe just a spreadsheet) where we include info on replacements/upgrades/maintanance of sensors etc. I suggest we go backwards starting from the setup we have today and then we try to find info on when stuff has been replaced etc. Tracing these changes should probably be related to when the data structure (e.g. no of columns in the .dat-files) has been chagned.

As we now harmonize the data, This info is now essential.

**Comment by JuliaKukulies** [comment]
Yes, sounds like a good idea! I started a spreadsheet (metadata_sensors.xlxs) with a list of sensors and setup per climate variable and station for different periods. Feel free to change the structure of the file or to add any information on the sensors if you have more information (e.g. on the sensors of the bridge station before March 2013). Otherwise I try to track as much as possible based on the columns in the .dat files.

**Comment by biglimp** [comment]
Great. Can you make me admin (or something) so that I can push my changes.

**Comment by JuliaKukulies** [comment]
Yes! Does it work now to commit and push?

**Comment by biglimp** [comment]
Yes, thanks. We should try to get Per into this repo, or at least send him the xls-sheet so that he can fill it in also. I close this issue.
